spring:
  profiles:
    active: dev
#  thymeleaf:
#    mode: HTML5
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html

school:
  name: 天一中学
  address: 无锡
rank:
  name: 黄金
server:
  port: 8081



